// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_250_dots = "CgkIxvjEm5YGEAIQDg"; // <GPGSID>
        public const string leaderboard_circle_tapping = "CgkIxvjEm5YGEAIQBw"; // <GPGSID>
        public const string leaderboard_multiple_dots = "CgkIxvjEm5YGEAIQCQ"; // <GPGSID>
        public const string achievement_100 = "CgkIxvjEm5YGEAIQCw"; // <GPGSID>
        public const string achievement_less_than_02_seconds = "CgkIxvjEm5YGEAIQBQ"; // <GPGSID>
        public const string achievement_50_dots = "CgkIxvjEm5YGEAIQCg"; // <GPGSID>
        public const string achievement_150 = "CgkIxvjEm5YGEAIQDA"; // <GPGSID>
        public const string leaderboard_screen_tapping = "CgkIxvjEm5YGEAIQCA"; // <GPGSID>
        public const string achievement_200_dots = "CgkIxvjEm5YGEAIQDQ"; // <GPGSID>
        public const string achievement_350_dots = "CgkIxvjEm5YGEAIQEA"; // <GPGSID>
        public const string achievement_impossible = "CgkIxvjEm5YGEAIQBg"; // <GPGSID>
        public const string achievement_under_a_second = "CgkIxvjEm5YGEAIQAQ"; // <GPGSID>
        public const string achievement_under_05_seconds = "CgkIxvjEm5YGEAIQAg"; // <GPGSID>
        public const string achievement_under_04_seconds = "CgkIxvjEm5YGEAIQAw"; // <GPGSID>
        public const string achievement_under_03_seconds = "CgkIxvjEm5YGEAIQBA"; // <GPGSID>
        public const string achievement_300_dots = "CgkIxvjEm5YGEAIQDw"; // <GPGSID>
        public const string achievement_400_dots = "CgkIxvjEm5YGEAIQEQ"; // <GPGSID>

}

